In [1]:
# Install libraries

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\vamsi\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vamsi\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vamsi\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Import libraries and load dataset

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/vamsi/Downloads/SuperStoreOrders.csv/SuperStoreOrders.csv")

In [4]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,01-01-2011,06-01-2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,01-01-2011,08-01-2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,01-01-2011,05-01-2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,01-01-2011,05-01-2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,01-01-2011,08-01-2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [5]:
# View dataset structure

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [8]:
df.shape

(51290, 21)

In [9]:
df.describe()

           quantity      discount        profit  shipping_cost          year
count  51290.000000  51290.000000  51290.000000   51290.000000  51290.000000
mean       3.476545      0.142908     28.641740      26.375915   2012.777208
std        2.278766      0.212280    174.424113      57.296804      1.098931
min        1.000000      0.000000  -6599.978000       0.000000   2011.000000
25%        2.000000      0.000000      0.000000       2.610000   2012.000000
50%        3.000000      0.000000      9.240000       7.790000   2013.000000
75%        5.000000      0.200000     36.810000      24.450000   2014.000000
max       14.000000      0.850000   8399.976000     933.570000   2014.000000

In [10]:
# Convert Date datatypes

In [11]:
df['order_date']=pd.to_datetime(df['order_date'], dayfirst=True)

In [13]:
df.head(2)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01,06-01-2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,2011-01-01,08-01-2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011

In [14]:
df['ship_date']=pd.to_datetime(df['ship_date'], dayfirst=True)

In [15]:
df.head(2)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011

In [17]:
# Fix sales column values, remove commas and extra symbols

In [19]:
df['sales']=df['sales'].replace('[$/,]','',regex=True).astype(float)

In [20]:
df.head(2)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408.0,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120.0,3,0.1,36.036,9.72,Medium,2011

In [21]:
# Chesk missing values

In [22]:
df.isnull().sum()

order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_name     0
segment           0
state             0
country           0
market            0
region            0
product_id        0
category          0
sub_category      0
product_name      0
sales             0
quantity          0
discount          0
profit            0
shipping_cost     0
order_priority    0
year              0
dtype: int64

In [23]:
# Note:- There is no null values in data set

In [24]:
# Find duplicate rows

In [25]:
df.duplicated().sum()

np.int64(0)

In [26]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_name, segment, state, country, market, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit, shipping_cost, order_priority, year]
Index: []

[0 rows x 21 columns]

In [27]:
df[df.duplicated()]

Empty DataFrame
Columns: [order_id, order_date, ship_date, ship_mode, customer_name, segment, state, country, market, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit, shipping_cost, order_priority, year]
Index: []

[0 rows x 21 columns]

In [28]:
# Note:- There are no duplicated rows

In [29]:
# Create New Columns

In [30]:
# Delivery time - Shipping time analysis

In [32]:
df['Delivery_days']=(df['ship_date']-df['order_date']).dt.days

In [33]:
df.head(2)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,Delivery_days
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408.0,2,0.0,106.140,35.46,Medium,2011,5
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Supplies,"Acme Trimmer, High Speed",120.0,3,0.1,36.036,9.72,Medium,2011,7

In [34]:
# Profit ratio

In [35]:
df['profit_ratio']=df['profit']/df['sales']*100

In [36]:
df.head(2)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,Delivery_days,profit_ratio
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,"Tenex Lockers, Blue",408.0,2,0.0,106.140,35.46,Medium,2011,5,26.014706
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,"Acme Trimmer, High Speed",120.0,3,0.1,36.036,9.72,Medium,2011,7,30.030000

In [37]:
# Extract order month and year

In [39]:
df['order_month']=df['order_date'].dt.month
df['order_year']=df['order_date'].dt.year

In [41]:
df.head(2)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,quantity,discount,profit,shipping_cost,order_priority,year,Delivery_days,profit_ratio,order_month,order_year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,2,0.0,106.140,35.46,Medium,2011,5,26.014706,1,2011
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,3,0.1,36.036,9.72,Medium,2011,7,30.030000,1,2011

In [90]:
# Delete unnecessary columns

In [91]:
df.drop([
    'order_id',
    'customer_name',
    'product_id',
    'market',
    'order_priority'
], axis=1, inplace=True)

In [69]:
# EDA -- Exploratory Data Analysis

In [43]:
# Count number of orders in each category . Which category is most frequently sold

In [75]:
df['category'].value_counts()

category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [ ]:
# See which products are ordered most. Identify high-demand product types

In [45]:
df['sub_category'].value_counts()

sub_category
Binders        6152
Storage        5059
Art            4883
Paper          3538
Chairs         3434
Phones         3357
Furnishings    3170
Accessories    3075
Labels         2606
Envelopes      2435
Supplies       2425
Fasteners      2420
Bookcases      2411
Copiers        2223
Appliances     1755
Machines       1486
Tables          861
Name: count, dtype: int64

In [46]:
# Count orders by region. Which region has most activity

In [47]:
df['region'].value_counts()

region
Central           11117
South              6645
EMEA               5029
North              4785
Africa             4587
Oceania            3487
West               3203
Southeast Asia     3129
East               2848
North Asia         2338
Central Asia       2048
Caribbean          1690
Canada              384
Name: count, dtype: int64

In [48]:
# Understand customer base. Which segment dominates (Consumer, Corporate, etc.)

In [50]:
df['segment'].value_counts()

segment
Consumer       26518
Corporate      15429
Home Office     9343
Name: count, dtype: int64

In [51]:
# See most used shipping method. Preferred delivery mode

In [52]:
df['ship_mode'].value_counts()

ship_mode
Standard Class    30775
Second Class      10309
First Class        7505
Same Day           2701
Name: count, dtype: int64

In [53]:
# Count orders per year. Business growth (more orders = growth)

In [54]:
df['order_year'].value_counts()

order_year
2014    17531
2013    13799
2012    10962
2011     8998
Name: count, dtype: int64

In [55]:
# Count monthly orders. Peak business months

In [59]:
df['order_month'].value_counts()

order_month
11    6342
12    6302
9     5975
6     5331
8     5078
10    4490
5     3747
7     3166
4     3057
3     3035
1     2599
2     2168
Name: count, dtype: int64

In [61]:
df['order_month'].value_counts().sort_index()

order_month
1     2599
2     2168
3     3035
4     3057
5     3747
6     5331
7     3166
8     5078
9     5975
10    4490
11    6342
12    6302
Name: count, dtype: int64

In [125]:
df['discount'].value_counts()

discount
0.000    29009
0.200     4998
0.100     4068
0.400     3177
0.600     2006
0.700     1786
0.500     1633
0.170      735
0.470      725
0.150      541
0.002      461
0.270      388
0.300      340
0.450      327
0.800      316
0.250      198
0.070      150
0.350      122
0.402      104
0.370       74
0.202       41
0.320       27
0.602       23
0.650       17
0.570       12
0.550       10
0.850        2
Name: count, dtype: int64

In [ ]:
# Analyze data by using Groupby()

In [ ]:
# category wise sales

In [73]:
df.groupby('category')['sales'].sum()

category
Furniture          4110884.0
Office Supplies    3787330.0
Technology         4744691.0
Name: sales, dtype: float64

In [ ]:
# Region wise sales

In [82]:
df.groupby('region')['sales'].sum()

region
Africa             783776.0
Canada              66932.0
Caribbean          324281.0
Central           2822399.0
Central Asia       752839.0
EMEA               806184.0
East               678834.0
North             1248192.0
North Asia         848349.0
Oceania           1100207.0
South             1600960.0
Southeast Asia     884438.0
West               725514.0
Name: sales, dtype: float64

In [87]:
# groupby() with multiple aggregations

In [95]:
# Analyze Category wise sales,profits,orders

In [88]:
df.groupby('category').agg({
    'sales': 'sum',
    'profit': 'sum',
    'category': 'count'
})

                     sales        profit  category
category
Furniture        4110884.0  286782.25380      9876
Office Supplies  3787330.0  518473.83430     31273
Technology       4744691.0  663778.73318     10141

In [96]:
# Analyze sub-category wise sales,profits,orders

In [89]:
df.groupby('sub_category').agg({
    'sales': 'sum',
    'profit': 'sum',
    'sub_category': 'count'
})

                  sales        profit  sub_category
sub_category
Accessories    749307.0  129626.30620          3075
Appliances    1011081.0  141680.58940          1755
Art            372163.0   57953.91090          4883
Binders        461952.0   72449.84600          6152
Bookcases     1466559.0  161924.41950          2411
Chairs        1501682.0  141973.79750          3434
Copiers       1509439.0  258567.54818          2223
Envelopes      170926.0   29601.11630          2435
Fasteners       83254.0   11525.42410          2420
Furnishings    385609.0   46967.42550          3170
Labels          73433.0   15010.51200          2606
Machines       779071.0   58867.87300          1486
Paper          244307.0   59207.68270          3538
Phones        1706874.0  216717.00580          3357
Storage       1127124.0  108461.48980          5059
Supplies       243090.0   22583.26310          2425
Tables         757034.0  -64083.38870           861

In [ ]:
# Sales of top 10 products

In [143]:
df.groupby('product_name')['sales'].sum().sort_values(ascending=False).head(10)

product_name
Apple Smart Phone, Full Size                                86936.0
Cisco Smart Phone, Full Size                                76441.0
Motorola Smart Phone, Full Size                             73159.0
Nokia Smart Phone, Full Size                                71904.0
Canon imageCLASS 2200 Advanced Copier                       61600.0
Hon Executive Leather Armchair, Adjustable                  58200.0
Office Star Executive Leather Armchair, Adjustable          50667.0
Harbour Creations Executive Leather Armchair, Adjustable    50120.0
Samsung Smart Phone, Cordless                               48654.0
Nokia Smart Phone, with Caller ID                           47880.0
Name: sales, dtype: float64

In [145]:
# Profits of top 10 products

In [146]:
df.groupby('product_name')['profit'].sum().sort_values(ascending=False).head(10)

product_name
Canon imageCLASS 2200 Advanced Copier                       25199.9280
Cisco Smart Phone, Full Size                                17238.5206
Motorola Smart Phone, Full Size                             17027.1130
Hoover Stove, Red                                           11807.9690
Sauder Classic Bookcase, Traditional                        10672.0730
Harbour Creations Executive Leather Armchair, Adjustable    10427.3260
Nokia Smart Phone, Full Size                                 9938.1955
Cisco Smart Phone, with Caller ID                            9786.6408
Nokia Smart Phone, with Caller ID                            9465.3257
Belkin Router, USB                                           8955.0180
Name: profit, dtype: float64

In [97]:
# Analyze Region wise sales.profits,orders

In [99]:
df.groupby('region').agg({
    'sales': 'sum',
    'profit': 'sum',
    'region': 'count'
})

                    sales        profit  region
region
Africa           783776.0   88871.63100    4587
Canada            66932.0   17817.39000     384
Caribbean        324281.0   34571.32104    1690
Central         2822399.0  311403.98164   11117
Central Asia     752839.0  132480.18700    2048
EMEA             806184.0   43897.97100    5029
East             678834.0   91522.78000    2848
North           1248192.0  194597.95252    4785
North Asia       848349.0  165578.42100    2338
Oceania         1100207.0  121666.64200    3487
South           1600960.0  140355.76618    6645
Southeast Asia   884438.0   17852.32900    3129
West             725514.0  108418.44890    3203

In [98]:
# Analyze country wise sales,orders,profits

In [169]:
df.groupby('country').agg({'sales':'sum','profit':'sum','country':'count'})

               sales       profit  country
country
Afghanistan  21674.0   5460.30000       55
Albania       3888.0    709.32000       16
Algeria      36090.0   9106.50000      196
Angola       25551.0   6494.97000      122
Argentina    57510.0 -18693.79672      390
...              ...          ...      ...
Venezuela    26587.0 -11222.71044      194
Vietnam      65802.0  -1870.23060      265
Yemen         2464.0  -3706.45800       30
Zambia       26029.0   7001.73000      102
Zimbabwe      3767.0  -5428.78500       80

[147 rows x 3 columns]

In [104]:
# Segment wise sales,profits,orders

In [105]:
df.groupby('segment').agg({
    'sales': 'sum',
    'profit': 'sum',
    'segment': 'count'
})

                 sales        profit  segment
segment
Consumer     6508141.0  749239.78206    26518
Corporate    3824808.0  442785.85866    15429
Home Office  2309956.0  277009.18056     9343

In [113]:
# Month wise sales.profits,orders

In [114]:
df.groupby('order_month').agg({
    'sales': 'sum','profit':'sum',
    'order_month': 'count'
})

                 sales        profit  order_month
order_month
1             675141.0   73535.38454         2599
2             543768.0   72509.72922         2168
3             770519.0   94087.52096         3035
4             698603.0   73513.63124         3057
5             904061.0  104509.78428         3747
6            1269751.0  147079.41684         5331
7             749423.0   78070.09172         3166
8            1293852.0  151854.10972         5078
9            1437432.0  170438.18316         5975
10           1168220.0  157269.35838         4490
11           1551319.0  175449.48412         6342
12           1580816.0  170718.12710         6302

In [ ]:
# Which shipping mode is mostly used and which is fastest delivery

In [120]:
df.groupby('ship_mode').agg({
    'Delivery_days': 'mean',
    'ship_mode': 'count'
})

                Delivery_days  ship_mode
ship_mode
First Class          2.181746       7505
Same Day             0.037394       2701
Second Class         3.230187      10309
Standard Class       4.998018      30775

In [ ]:
# Discount impact --(high discount --> low profit)

In [128]:
df.groupby('discount').agg({
    'sales': 'sum',
    'profit': 'mean',
    'discount': 'count'
})

              sales       profit  discount
discount
0.000     6992734.0    61.039514     29009
0.002      261395.0   125.762649       461
0.070      121620.0   140.990022       150
0.100     1579618.0    64.071216      4068
0.150      306037.0    50.602409       541
0.170      247404.0    38.317107       735
0.200     1203855.0    23.552594      4998
0.202       16213.0   -14.518847        41
0.250       88063.0     4.043371       198
0.270       89351.0    -4.317213       388
0.300      188913.0   -57.899557       340
0.320       14491.0   -88.560656        27
0.350       95704.0  -116.144693       122
0.370       31615.0   -78.462191        74
0.400      559557.0   -45.246603      3177
0.402       33737.0  -109.908138       104
0.450       33397.0   -41.610973       327
0.470       83432.0   -42.982420       725
0.500      324145.0   -97.140158      1633
0.550        6308.0  -315.067200        10
0.570        8144.0  -526.129000        12
0.600      184586.0   -81.732147      2006
0.602        4977.0  -213.279085        23
0.650        6580.0  -365.997971        17
0.700      139770.0  -104.339576      1786
0.800       20462.0  -122.203244       316
0.850         797.0 -1534.329000         2

In [147]:
# INSIGHTS

In [177]:
# Highest orders in category
high_order_category=df['category'].value_counts().idxmax()
print('Highest orders in category is:', high_order_category)

# Highest orders in sub_category
high_order_sub_category=df['sub_category'].value_counts().idxmax()
print('Highest orders in sub-category is:', high_order_sub_category)

# top region with high orders
top_region=df['region'].value_counts().idxmax()
print('Top region with high orders is:', top_region)

# top segment with high orders
top_segment=df['segment'].value_counts().idxmax()
print('Top segment with high orders is:', top_segment)

# mostly used ship mode to deliver
top_ship_mode=df['ship_mode'].value_counts().idxmax()
print('Top most used ship mode is:', top_ship_mode)

# Peak business month with high orders
top_month=df['order_month'].value_counts().idxmax()
print('Peak business month with high orders is:', top_month)

# Highest sales category
high_sale_category = df.groupby('category')['sales'].sum().idxmax()
print('Highest sales category is:', high_sale_category)

# Highest profits category
high_profit_category = df.groupby('category')['profit'].sum().idxmax()
print('Highest profits category is:', high_profit_category)

# subcategory wise highest sales, profits, orders
high_sub_category_sales_profits_orders = df.groupby('sub_category').agg({'sales':'sum','profit':'sum','sub_category':'count'}).idxmax()
print('Highest sub-category wise sales profits orders are:', high_sub_category_sales_profits_orders)

# Region wise highest profits , sales, orders
high_region_sales_profits_orders = df.groupby('region').agg({'sales':'sum','profit':'sum','region':'count'}).idxmax()
print('Highest Region wise sales profits orders are:', high_region_sales_profits_orders)

# Country wise highest profit, sales, orders
high_country_sales_profits_orders = df.groupby('country').agg({'sales':'sum','profit':'sum','country':'count'}).idxmax()
print('Highest country wise sales profits orders are:', high_country_sales_profits_orders)

# State wise highest sales, profit, orders
high_state_sales_profits_orders = df.groupby('state').agg({'sales':'sum','profit':'sum','state':'count'}).idxmax()
print('Highest state wise sales profits orders are:', high_state_sales_profits_orders)

# Top most month with highest sales, profits,orders
high_month_sales_profits_orders = df.groupby('order_month').agg({'sales':'sum','profit':'sum','order_month':'count'}).idxmax()
print('Top most month with highest sales profits orders are:', high_month_sales_profits_orders)

# Top most year with highest sales, profits,orders
high_year_sales_profits_orders = df.groupby('order_year').agg({'sales':'sum','profit':'sum','order_year':'count'}).idxmax()
print('Top most year with highest sales profits orders are:', high_year_sales_profits_orders)

# Top most year with highest sales, profits,orders
high_product_sales_profits_orders = df.groupby('product_name').agg({'sales':'sum','profit':'sum','product_name':'count'}).idxmax()
print('Top most product with highest sales profits orders are:', high_product_sales_profits_orders)

# Discount given with highest profit
high_discount_sales_profits_orders = df.groupby('discount').agg({'sales':'sum','profit':'mean','discount':'count'}).idxmax()
print('Top most discount with highest sales profits orders are:', high_discount_sales_profits_orders)

Highest orders in category is: Office Supplies
Highest orders in sub-category is: Binders
Top region with high orders is: Central
Top segment with high orders is: Consumer
Top most used ship mode is: Standard Class
Peak business month with high orders is: 11
Highest sales category is: Technology
Highest profits category is: Technology
Highest sub-category wise sales profits orders are: sales            Phones
profit          Copiers
sub_category    Binders
dtype: object
Highest Region wise sales profits orders are: sales     Central
profit    Central
region    Central
dtype: object
Highest country wise sales profits orders are: sales      United States
profit     United States
country    United States
dtype: object
Highest state wise sales profits orders are: sales        England
profit       England
state     California
dtype: object
Top most month with highest sales profits orders are: sales          12
profit         11
order_month    11
dtype: int32
Top most year with highest sales profits orders are: sales         2014
profit        2014
order_year    2014
dtype: int32
Top most product with highest sales profits orders are: sales                    Apple Smart Phone, Full Size
profit          Canon imageCLASS 2200 Advanced Copier
product_name                                  Staples
dtype: object
Top most discount with highest sales profits orders are: sales       0.00
profit      0.07
discount    0.00
dtype: float64

In [178]:
# Save the data

In [179]:
df.to_csv("C:/Users/vamsi/Downloads/SuperStoreOrders.csv/SuperStoreOrders.csv", index=False)